version: "3"

services:
  vrising:
    image: bjg96/vrising-server:latest
    container_name: vrising-server
    volumes:
      - /app/V-Rising-Docker-Linux/data:/data
    ports:
      - 37015:27015
      - 37016:27016
    restart: unless-stopped
    tty: true
