version: "3"

services:
  vrising:
    image: bjg96/vrising-server:latest
    container_name: vrising-server
    volumes:
      - /app/V-Rising-Docker-Linux/data:/data
    ports:
      - 27015:27015/udp
      - 27015:27015/tcp
      - 27036:27036/tcp
      - 27016:27016/udp
      - 27031:27031/udp
      - 27032:27032/udp
      - 27033:27033/udp
      - 27034:27034/udp
      - 27035:27035/udp
      - 27036:27036/udp
    restart: unless-stopped
    tty: true
